name: Linux_CMake

on:
  push:
    branches: [ "add/github_action_linux" ]
  pull_request:
    branches: [ "add/github_action_linux" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install libraries
      run: |
          sudo apt-get update
          sudo apt-get install libhdf5-serial-dev libtiff-dev python3 python3-pip
          python -m pip install --upgrade pip setuptools wheel

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake
            -B ${{github.workspace}}/build
            -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install
            -D mcnptools.cpack=ON
            -D mcnptools.python=ON
            -D mcnptools.python_install=Prefix

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j

    - name: Build Wheel
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/build/python && python setup${{env.BUILD_TYPE}}.py bdist_wheel

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
           cmake --build build --config Release -t pytest

    - name: Install
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Pack
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cpack -G ZIP

    - name: Capture artifacts
      uses: actions/upload-artifact@v3

      with:
          name: mcnptools
          path: |
              ${{github.workspace}}/build/*.zip
              ${{github.workspace}}/build/python/dist/*.whl
